version: '3.8'
services:
  rl-env:
    build:
      context: .
      dockerfile: Dockerfile.linux
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true
